trigger:
  - master
  - releases/*
pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    git pull
    npm run build
    sudo systemctl restart pulsive_api
  displayName: 'git pull and npm run build and sudo systemctl restart pulsive_api'