version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    container_name: db
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  postgres_test:
    image: postgres:10.3
    restart: always
    container_name: db_test
    env_file:
      - ./.env.test
    ports:
      - '5433:5432'
  api:
    container_name: api
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  postgres:
