version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
